language: python
python:
  - "2.7"
cache: apt

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y sshfs curl
  - curl -sSL https://get.docker.io/ubuntu/ | sudo sh
  - sudo pip install -r requirements.txt
  - sudo pip install -e .
  - sudo service docker start
  - sudo mkdir -p /var/lib/docker
  - echo exit 101 | sudo tee /usr/sbin/policy-rc.d
  - sudo chmod +x /usr/sbin/policy-rc.d

script: sudo py.test tests.py -v

notifications:
  email:
    on_success: change
    on_failure: change
